# Generated by Django 3.0.4 on 2020-03-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Paper_Consumption', 'paper_consumed', 'amount'),
        migrations.RenameField('Paper_Incoming', 'paper_income', 'amount')

    ]
