# Generated by Django 3.0.7 on 2020-06-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('paper_type', 'grammage', 'paper_format', 'company')},
        ),
    ]
