# Generated by Django 3.0.4 on 2020-03-14 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Raw_Material_Producer_Company', 'Paper_Producer')
    ]
