# Generated by Django 3.0.7 on 2020-06-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20200608_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_format',
            name='format',
            field=models.PositiveSmallIntegerField(help_text='format of paper', unique=True),
        ),
        migrations.AlterField(
            model_name='paper_grammage',
            name='grammage',
            field=models.PositiveSmallIntegerField(help_text='grammage of paper', unique=True),
        ),
        migrations.AlterField(
            model_name='paper_producer',
            name='name',
            field=models.CharField(help_text='raw material producer company name', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='paper_producer',
            name='short_name',
            field=models.CharField(default='short_code', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper_type',
            name='code',
            field=models.CharField(help_text='paper type code eg: K, S, N or Ks', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paper_type',
            name='name',
            field=models.CharField(help_text='paper type name eg: CMP, KLB', max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='paper_producer',
            unique_together={('name', 'short_name')},
        ),
        migrations.AlterUniqueTogether(
            name='paper_type',
            unique_together={('name', 'code')},
        ),
    ]
