# Generated by Django 3.0.7 on 2020-06-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20200608_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper_format',
            options={'ordering': ['format']},
        ),
        migrations.AlterModelOptions(
            name='paper_grammage',
            options={'ordering': ['grammage']},
        ),
        migrations.AlterModelOptions(
            name='paper_producer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='paper_type',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='roll',
            name='roll_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
