# Generated by Django 3.0.7 on 2020-06-17 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20200608_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='current_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='roll',
            name='initial_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
