# Generated by Django 3.0.7 on 2020-06-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20200617_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll_consumption',
            name='status',
            field=models.CharField(choices=[('p', 'production'), ('c', 'consumed')], default='p', help_text='Roll Status', max_length=1),
        ),
    ]
