# Generated by Django 3.0.7 on 2020-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_roll_consumption_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='instance_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
