# Generated by Django 3.0.7 on 2020-07-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_roll_instance_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roll_consumption',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='roll_incoming',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='roll_return',
            options={'ordering': ['id']},
        ),
    ]
