# Generated by Django 3.0.7 on 2020-08-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_orderdelivery'),
        ('warehouse', '0008_auto_20200710_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll_consumption',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Order'),
        ),
    ]
