# Generated by Django 3.0.7 on 2020-08-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0009_auto_20200824_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('final_producer_amount', models.PositiveSmallIntegerField(default=0)),
                ('corrugator_amount', models.PositiveSmallIntegerField(default=0)),
                ('corrugator_defect', models.PositiveSmallIntegerField(default=0)),
                ('flex_amount', models.PositiveSmallIntegerField(default=0)),
                ('flex_defect', models.PositiveSmallIntegerField(default=0)),
                ('thompson_amount', models.PositiveSmallIntegerField(default=0)),
                ('thompson_defect', models.PositiveSmallIntegerField(default=0)),
                ('glue_amount', models.PositiveSmallIntegerField(default=0)),
                ('glue_defect', models.PositiveSmallIntegerField(default=0)),
                ('stitching_amount', models.PositiveSmallIntegerField(default=0)),
                ('stitching_defect', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Order')),
            ],
        ),
        migrations.CreateModel(
            name='StitchingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_date', models.DateField()),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('defect', models.PositiveSmallIntegerField(default=0)),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.Production')),
            ],
        ),
        migrations.CreateModel(
            name='GlueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_date', models.DateField()),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('defect', models.PositiveSmallIntegerField(default=0)),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.Production')),
            ],
        ),
        migrations.CreateModel(
            name='FlexHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_date', models.DateField()),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('defect', models.PositiveSmallIntegerField(default=0)),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.Production')),
            ],
        ),
        migrations.CreateModel(
            name='CorrugatorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_date', models.DateField()),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('defect', models.PositiveSmallIntegerField(default=0)),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.Production')),
            ],
        ),
    ]
