# Generated by Django 3.0.7 on 2020-08-25 11:28

from django.db import migrations


def forwards(apps, schema_editor):
    Model = apps.get_model('production', 'Production')
    for i, obj in enumerate(Model.objects.all()):
        obj.production_id = f'p{i}'
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('production', '0004_production_production_id'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
