# Generated by Django 3.0.7 on 2020-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20200825_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='production_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
