# Generated by Django 3.0.4 on 2020-03-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='company name')),
            ],
        ),
        migrations.CreateModel(
            name='PaperConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaperFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.PositiveSmallIntegerField(verbose_name='format of paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperGrammage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammage', models.PositiveSmallIntegerField(verbose_name='grammage of paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperIncomeRemainingFromProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaperIncoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='paper type name eg: CMP, KLB')),
                ('code', models.CharField(max_length=10, verbose_name='paper type code eg: K, S, N or Ks')),
                ('description', models.CharField(max_length=100, verbose_name='paper type description eg: corrugated paper, cellulose')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_amount', models.PositiveIntegerField(verbose_name='current amount of paper')),
                ('paper_amount_remained_from_last_month', models.PositiveIntegerField(verbose_name='amount of paper remained from last month')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Company', verbose_name='company produced which paper ')),
                ('grammage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.PaperGrammage', verbose_name=' paper grammage: 120-145')),
                ('paper_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.PaperFormat', verbose_name='paper format: 800-1450')),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.PaperType', verbose_name='paper type: KLB, CMP')),
            ],
        ),
    ]
