# Generated by Django 3.0.4 on 2020-03-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwproone_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='company name', max_length=150),
        ),
    ]
