# Generated by Django 3.0.4 on 2020-03-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwproone_backend', '0002_auto_20200309_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='company',
            field=models.ForeignKey(help_text='company produced which paper ', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Company'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='grammage',
            field=models.ForeignKey(help_text=' paper grammage: 120-145', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.PaperGrammage'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_amount_remained_from_last_month',
            field=models.PositiveIntegerField(help_text='amount of paper remained from last month'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_format',
            field=models.ForeignKey(help_text='paper format: 800-1450', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.PaperFormat'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.ForeignKey(help_text='paper type: KLB, CMP', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.PaperType'),
        ),
        migrations.AlterField(
            model_name='paperformat',
            name='format',
            field=models.PositiveSmallIntegerField(help_text='format of paper'),
        ),
        migrations.AlterField(
            model_name='papergrammage',
            name='grammage',
            field=models.PositiveSmallIntegerField(help_text='grammage of paper'),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='code',
            field=models.CharField(help_text='paper type code eg: K, S, N or Ks', max_length=10),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='description',
            field=models.CharField(help_text='paper type description eg: corrugated paper, cellulose', max_length=100),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='name',
            field=models.CharField(help_text='paper type name eg: CMP, KLB', max_length=20),
        ),
    ]
