# Generated by Django 3.0.4 on 2020-03-08 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwproone_backend', '0003_auto_20200309_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperconsumption',
            name='paper',
            field=models.ForeignKey(default=1, help_text='Paper that is Consumed', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Paper'),
        ),
        migrations.AddField(
            model_name='paperconsumption',
            name='paper_consumed',
            field=models.PositiveIntegerField(default=0, help_text='consumed amount of paper'),
        ),
        migrations.AddField(
            model_name='paperincomeremainingfromproduction',
            name='paper',
            field=models.ForeignKey(default=1, help_text='Paper that is Income from production', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Paper'),
        ),
        migrations.AddField(
            model_name='paperincomeremainingfromproduction',
            name='paper_income_production',
            field=models.PositiveIntegerField(default=0, help_text='income amount of paper from production'),
        ),
        migrations.AddField(
            model_name='paperincoming',
            name='paper',
            field=models.ForeignKey(default=1, help_text='Paper that is Income', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Paper'),
        ),
        migrations.AddField(
            model_name='paperincoming',
            name='paper_income',
            field=models.PositiveIntegerField(default=0, help_text='income amount of paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_amount',
            field=models.PositiveIntegerField(help_text='current amount of paper'),
        ),
    ]
