# Generated by Django 3.0.4 on 2020-03-11 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dwproone_backend', '0004_auto_20200309_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Measurement unit kg or litre or ton', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material_incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' ', max_length=100)),
                ('amount', models.PositiveIntegerField(help_text=' ')),
                ('amount_remained_from_last_month', models.PositiveIntegerField(help_text=' ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='paperconsumption',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 11, 6, 39, 20, 453121, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperincomeremainingfromproduction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paperincoming',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Raw_material_remaining_from_production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' ', max_length=100)),
                ('amount', models.PositiveIntegerField(help_text=' ')),
                ('measurement_id', models.ForeignKey(help_text=' ', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Measure_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material_consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' ', max_length=100)),
                ('amount', models.PositiveIntegerField(help_text=' ')),
                ('measurement_id', models.ForeignKey(help_text=' ', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Measure_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of raw material vox, bura and etc', max_length=100)),
                ('amount', models.PositiveIntegerField(help_text='current amount of Raw Material')),
                ('amount_remained_from_last_month', models.PositiveIntegerField(help_text='remained from last month amount of Raw Material')),
                ('measurement_id', models.ForeignKey(help_text='foreign key id to measurement', on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Measure_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Ink_incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('measurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Measure_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Ink_consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('measurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Measure_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Ink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('amount_remained_from_last_month', models.PositiveIntegerField()),
                ('measurement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwproone_backend.Measure_unit')),
            ],
        ),
    ]
