# Generated by Django 3.0.7 on 2020-08-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveSmallIntegerField(help_text='box length')),
                ('width', models.PositiveSmallIntegerField(help_text='box width')),
                ('height', models.PositiveSmallIntegerField(help_text='box height')),
                ('configuration', models.CharField(help_text='box configuration, KSS SSS KSSSK', max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='contract number DPC LB 190503', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='customer name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('ship_date', models.DateField()),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('remaining', models.PositiveSmallIntegerField()),
                ('delivered', models.PositiveSmallIntegerField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Box')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Customer'),
        ),
        migrations.AddField(
            model_name='box',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Customer'),
        ),
    ]
