# Generated by Django 3.0.7 on 2020-08-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200805_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='customer name', max_length=100, unique=True),
        ),
    ]
