# Generated by Django 3.0.7 on 2020-08-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200806_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='dimension',
            field=models.CharField(default='1000x1000x1000', help_text='box dimension length*width*height', max_length=20),
        ),
    ]
