# Generated by Django 3.0.7 on 2020-08-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_box_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(help_text='contract number DPC LB 190503', max_length=200, unique=True),
        ),
    ]
