# Generated by Django 3.0.7 on 2020-08-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20200824_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='corrugator',
        ),
    ]
