# Generated by Django 3.0.7 on 2020-08-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_order_corrugator'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_id',
            field=models.CharField(default='box_id_default', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='short_name',
            field=models.CharField(default='box', max_length=10),
        ),
    ]
