# Generated by Django 3.0.7 on 2020-08-25 08:59

from django.db import models, migrations
from django.utils.text import slugify

from sales.models import Box


def forwards(apps, schema_editor):
    BoxModel = apps.get_model('sales', 'Box')
    for i, obj in enumerate(BoxModel.objects.all()):
        obj.box_id = f'{obj.customer.name}{i}'
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0012_customer_number_of_box_auto_increment'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
