# Generated by Django 3.0.7 on 2020-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20200825_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number_of_box_auto_increment',
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_box',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
