# Generated by Django 3.0.7 on 2020-08-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20200825_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
