# Generated by Django 3.0.7 on 2020-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20200825_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
